version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eventbooking-postgres
    environment:
      POSTGRES_DB: eventbooking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: eventbooking-user-service
    environment:
      PORT: "8081"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      DB_NAME: "eventbooking"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_SSL_MODE: "disable"
      JWT_SECRET: "your-secret-key-change-in-production"
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
